services:
      - type: web
        name: noswipe-backend
        env: python
        plan: starter
        buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
        startCommand: "gunicorn backend.wsgi:application"
        envVars:
          - key: DEBUG
            value: "False"
          - key: SECRET_KEY
            sync: false
          - key: DATABASE_URL
            sync: false
          - key: ALLOWED_HOSTS
            value: "noswipe.onrender.com"
          - key: PORT
            value: "8000"
      - type: web
        name: static
        env: static
        staticPublishPath: backend/staticfiles
        routes:
          - type: exact
            path: /static/
