services:
      - type: web
        name: noswipe-backend
        env: python
        plan: free
        buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
        startCommand: "gunicorn backend.wsgi:application"
        envVars:
          - key: DEBUG
            value: "False"
          - key: SECRET_KEY
            sync: false
          - key: DATABASE_URL
            sync: false
          - key: ALLOWED_HOSTS
            value: "your-backend.onrender.com"