# Generated by Django 5.0 on 2024-12-18 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.AddField(
            model_name="photo",
            name="is_profile_photo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="ethnicity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image_url",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_user",
        ),
    ]
