# Generated by Django 5.0 on 2024-12-18 13:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_dislikes_user_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="image_url",
        ),
        migrations.AddField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_photo_path
            ),
        ),
    ]
