# Generated by Django 5.0 on 2025-01-01 17:45

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_username_properly"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="ethnicity",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="features",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="image",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="is_profile_photo",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="user",
        ),
        migrations.AddField(
            model_name="photo",
            name="image_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="photo",
            name="age",
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                default="M",
                max_length=1,
                null=True,
            ),
        ),
    ]
