# Generated by Django 5.0 on 2025-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="image_url",
        ),
        migrations.AddField(
            model_name="photo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("B", "Both")],
                default="M",
                max_length=1,
                null=True,
            ),
        ),
    ]
